// This file is auto generated by build/build-entry.js
import Map from './map';
import config from './config';
import createComponent from './utils/createComponent';

const version = '0.1.0';

const components = [Map];

const install = function install(Vue, opts = {}) {
  if (install.installed) return;

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  config(opts || {});
};

// auto install
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export { install, version, config, createComponent, Map };

export default {
  install,
  version,
  config,
  createComponent,
};
